// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHyXZRVRsEeOhv_ZTzZMAsx1bcRxvNIJ8',
    appId: '1:279557303816:web:3734770492738c60f6abbd',
    messagingSenderId: '279557303816',
    projectId: 'mini-project-cf22a',
    authDomain: 'mini-project-cf22a.firebaseapp.com',
    storageBucket: 'mini-project-cf22a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV-9akV_0JzK1HzVhuHkE6_smRfnChDg4',
    appId: '1:279557303816:android:ebf63e8265254652f6abbd',
    messagingSenderId: '279557303816',
    projectId: 'mini-project-cf22a',
    storageBucket: 'mini-project-cf22a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvHAoYYcQ9jrB5mlNwRpgnULnf7ow7Heo',
    appId: '1:279557303816:ios:62f7369fc64efed3f6abbd',
    messagingSenderId: '279557303816',
    projectId: 'mini-project-cf22a',
    storageBucket: 'mini-project-cf22a.appspot.com',
    androidClientId: '279557303816-0iijib8s06o1u3r8hpvefsslsf44407p.apps.googleusercontent.com',
    iosClientId: '279557303816-doc5dt7jmn0lev3g4gfiibm4k403udtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvHAoYYcQ9jrB5mlNwRpgnULnf7ow7Heo',
    appId: '1:279557303816:ios:62f7369fc64efed3f6abbd',
    messagingSenderId: '279557303816',
    projectId: 'mini-project-cf22a',
    storageBucket: 'mini-project-cf22a.appspot.com',
    androidClientId: '279557303816-0iijib8s06o1u3r8hpvefsslsf44407p.apps.googleusercontent.com',
    iosClientId: '279557303816-doc5dt7jmn0lev3g4gfiibm4k403udtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
